name: Ejecutar pruebas Behave
run-name: Ejecutar pruebas Behave para comparar KPIs
on: 
  push:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'
        
    - name: Agregar ruta al PYTHONPATH
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/scripts

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas de Behave
      run: behave features/compararKpis.feature
